' DATA FOR MOUSE MOVEMENT X AND Y POSITIONS IN LESSON 2 SHOW ME STEPS :

xy = Array(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)

' Step 3: Mouse Moves To My Computer Icon
' starting X & Y coordinates:
xy(0) = 220
xy(1) = 250

' ending X & Y coordinates:
xy(2) = 48
xy(3) = 30


' Step 4: Mouse Moves To C: in My Computer Window
' ending X & Y coordinates:
xy(4) = 190
xy(5) = 170


' Step 5: Mouse Moves To My Documents in C: Window
xy(6) = 97
xy(7) = 166


' Step 6: Mouse Moves To File Menu
xy(8) = 85
xy(9) = 45

' Step 6: Mouse Moves To File-->New
xy(10) = 148
xy(11) = 70

' Step 6: Mouse Moves To File-->New-->Folder
xy(12) = 241
xy(13) = 72


' Step 7: Mouse Moves To New Folder Icon
xy(14) = 102
xy(15) = 181

' Step 7: Mouse Moves To 'Rename' in Popup Menu
xy(16) = 191
xy(17) = 361


' Step 8: Mouse Moves down to File-->New-->WordPad Document
xy(18) = 265
xy(19) = 135


' Step 9: Mouse Moves To New WordPad Document Icon
xy(20) = 215
xy(21) = 180

' Step 9: Mouse Moves To 'Rename' on Popup Menu
xy(22) = 253
xy(23) = 348


' Step 11: Mouse Moves To 'Sample File'
xy(24) = 215
xy(25) = 173

' Step 11: Mouse Drags Sample File to Sample Folder
' starting X & Y coordinates:
xy(26) = 170
xy(27) = 141
' ending X & Y coordinates:
xy(28) = 65
xy(29) = 147


' Step 12: Mouse Moves To 'Sample Folder'
xy(30) = 104
xy(31) = 177


' Step 13: Mouse Moves To Close Button
xy(32) = 498
xy(33) = 40

