' DATA FOR MOUSE MOVEMENT X AND Y POSITIONS IN LESSON 6 SHOW ME STEPS :

xy = Array(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)

' Step 3: Mouse moves to start button
' starting X & Y coordinates:
xy(0) = 220
xy(1) = 250
xy(2) = 25
xy(3) = 385

' Step 3: Mouse moves to Programs
xy(4) = 99
xy(5) = 60

' Step 3: Mouse moves across Programs to Accessories
xy(6) = 217
xy(7) = 52

' Step 3: Mouse moves across Acc menu
xy(8) = 350
xy(9) = 61

' Step 3: Mouse moves down to Wordpad
xy(10) = 340
xy(11) = 220


' Step 4: mouse moves to click in blank area of wordpad
xy(12) = 200
xy(13) = 175


' Step 5: MOUSE MOVES UP TO FILE MENU
xy(14) = 85
xy(15) = 44

' Step 5: MOUSE DOWN TO 'SAVE AS'
xy(16) = 162
xy(17) = 119


' Step 6: MOUSE MOVES TO TITLE BAR
xy(18) = 238
xy(19) = 50


' Step 7: MOUSE MOVES TO 'SAVE' BUTTON
xy(20) = 457
xy(21) = 255


' Step 8: MOUSE MOVES TO WORDPAD CLOSE BUTTON
xy(22) = 495
xy(23) = 23


' Step 9: MOUSE MOVES TO START BUTTON
xy(24) = 27
xy(25) = 391

' Step 9: MOUSE UP TO 'FIND'
xy(26) = 73
xy(27) = 203

' Step 9: MOUSE MOVES TO 'FILES OR FOLDERS'
xy(28) = 213
xy(29) = 195


' Step 10: MOUSE MOVES TO 'NAME & LOCATION' TAB
xy(30) = 106
xy(31) = 77


' Step 11: MOUSE MOVES TO 'LOOK IN' BOX
xy(32) = 358
xy(33) = 179

' Step 11: MOUSE DOWN TO C: DRIVE IN DROPDOWN BOX
xy(34) = 202
xy(35) = 279


' Step 12: MOUSE MOVES TO 'FIND NOW'
xy(36) = 450
xy(37) = 95


' Step 13: MOUSE MOVES TO 'THOMAS HARDY' FOUND DOCUMENT
xy(38) = 74
xy(39) = 274


' Step 14: MOUSE MOVES TO WORDPAD CLOSE BUTTON
xy(40) = 498
xy(41) = 25

' Step 14: MOUSE MOVES TO FIND DIALOG CLOSE BUTTON
xy(42) = 498
xy(43) = 25

